import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  // Cardio
  { id: "run", name: "Running", category: "cardio", mets: 9.8, distance_based: true },
  { id: "jog", name: "Jogging", category: "cardio", mets: 7.0, distance_based: true },
  { id: "cycle", name: "Cycling", category: "cardio", mets: 7.5, distance_based: true },
  { id: "walk", name: "Walking", category: "cardio", mets: 3.5 },
  { id: "hike", name: "Hiking", category: "cardio", mets: 6.0 },
  { id: "swim", name: "Swimming", category: "cardio", mets: 8.0 },
  { id: "row", name: "Rowing", category: "cardio", mets: 8.5 },
  { id: "jumprope", name: "Jump rope", category: "cardio", mets: 12.3 },
  { id: "hiit", name: "HIIT", category: "cardio", mets: 10.0 },
  { id: "stairs", name: "Stairs", category: "cardio", mets: 8.8 },
  { id: "elliptical", name: "Elliptical", category: "cardio", mets: 5.0 },
  { id: "skate", name: "Skating", category: "cardio", mets: 7.0 },
  { id: "ski", name: "Cross-country ski", category: "cardio", mets: 8.0 },

  // Gym
  { id: "squat", name: "Squats", category: "gym", mets: 5.0 },
  { id: "deadlift", name: "Deadlift", category: "gym", mets: 6.0 },
  { id: "bench", name: "Bench press", category: "gym", mets: 5.0 },
  { id: "plank", name: "Plank", category: "core", mets: 4.0 },
  { id: "ohp", name: "Overhead press", category: "gym", mets: 5.0 },
  { id: "lunge", name: "Lunges", category: "gym", mets: 5.5 },
  { id: "curl", name: "Bicep curl", category: "gym", mets: 3.5 },
  { id: "row_gym", name: "Barbell row", category: "gym", mets: 5.0 },
  { id: "legpress", name: "Leg press", category: "gym", mets: 5.0 },
  { id: "legcurl", name: "Leg curl", category: "gym", mets: 4.0 },
  { id: "legext", name: "Leg extension", category: "gym", mets: 4.0 },
  { id: "tricep", name: "Tricep dip", category: "gym", mets: 6.0 },
  { id: "latpull", name: "Lat pulldown", category: "gym", mets: 4.5 },
  { id: "calfraise", name: "Calf raise", category: "gym", mets: 3.5 },
  { id: "hipthrust", name: "Hip thrust", category: "gym", mets: 5.0 },
  { id: "kettlebell", name: "Kettlebell swing", category: "gym", mets: 9.8 },
  { id: "bulgarian", name: "Bulgarian split squat", category: "gym", mets: 5.5 },
  { id: "romanian", name: "Romanian deadlift", category: "gym", mets: 5.5 },
  { id: "frontsquat", name: "Front squat", category: "gym", mets: 5.5 },
  { id: "inclinebench", name: "Incline bench", category: "gym", mets: 5.0 },
  { id: "chestfly", name: "Cable fly", category: "gym", mets: 4.0 },
  { id: "shrug", name: "Shrug", category: "gym", mets: 3.5 },
  { id: "hyperext", name: "Hyperextension", category: "gym", mets: 4.0 },

  // Calisthenics
  { id: "pullup", name: "Pull-ups", category: "calisthenics", mets: 8.0 },
  { id: "pushup", name: "Push-ups", category: "calisthenics", mets: 8.0 },
  { id: "dip", name: "Dips", category: "calisthenics", mets: 8.0 },
  { id: "bodyweightsquat", name: "Bodyweight squats", category: "calisthenics", mets: 5.0 },
  { id: "burpee", name: "Burpees", category: "calisthenics", mets: 8.0 },
  { id: "muscleup", name: "Muscle-ups", category: "calisthenics", mets: 9.0 },
  { id: "handstandpushup", name: "Handstand push-ups", category: "calisthenics", mets: 8.0 },
  { id: "invertedrow", name: "Inverted rows", category: "calisthenics", mets: 6.0 },
  { id: "jumpingsquat", name: "Jump squats", category: "calisthenics", mets: 7.5 },
  { id: "pistol", name: "Pistol squats", category: "calisthenics", mets: 6.5 },

  // Core
  { id: "crunch", name: "Crunch", category: "core", mets: 4.5 },
  { id: "situp", name: "Sit-up", category: "core", mets: 4.5 },
  { id: "russian", name: "Russian twist", category: "core", mets: 5.0 },
  { id: "mountainclimber", name: "Mountain climber", category: "core", mets: 8.0 },
  { id: "legraise", name: "Hanging leg raise", category: "core", mets: 5.0 },
  { id: "bicycle", name: "Bicycle crunch", category: "core", mets: 5.5 },
  { id: "sideplank", name: "Side plank", category: "core", mets: 4.0 },
  { id: "woodchop", name: "Wood chop", category: "core", mets: 5.0 },
  { id: "flutterkick", name: "Flutter kick", category: "core", mets: 4.5 },

  // Sports
  { id: "basketball", name: "Basketball", category: "sports", mets: 6.5 },
  { id: "soccer", name: "Soccer", category: "sports", mets: 7.0 },
  { id: "tennis", name: "Tennis", category: "sports", mets: 7.3 },
  { id: "pingpong", name: "Table tennis", category: "sports", mets: 4.0 },
  { id: "badminton", name: "Badminton", category: "sports", mets: 5.5 },
  { id: "climb", name: "Climbing", category: "sports", mets: 8.0 },
  { id: "yoga", name: "Yoga", category: "sports", mets: 3.0 },
  { id: "pilates", name: "Pilates", category: "sports", mets: 3.0 },
  { id: "dance", name: "Dance", category: "sports", mets: 5.0 },
  { id: "box", name: "Boxing", category: "sports", mets: 9.0 },
  { id: "mma", name: "MMA", category: "sports", mets: 10.0 },
  { id: "volleyball", name: "Volleyball", category: "sports", mets: 6.0 },
  { id: "surf", name: "Surfing", category: "sports", mets: 6.0 },
  { id: "golf", name: "Golf", category: "sports", mets: 4.8 },
  { id: "football", name: "Flag football", category: "sports", mets: 6.0 },
  { id: "hockey", name: "Hockey", category: "sports", mets: 8.0 },
  { id: "martialarts", name: "Martial arts", category: "sports", mets: 8.0 },

  // Daily
  { id: "clean", name: "House cleaning", category: "daily", mets: 3.3 },
  { id: "garden", name: "Gardening", category: "daily", mets: 4.0 },
  { id: "walkdog", name: "Walk the dog", category: "daily", mets: 3.5 },
  { id: "desk", name: "Desk work", category: "daily", mets: 1.5 },
  { id: "carrygrocery", name: "Carrying groceries", category: "daily", mets: 3.5 },
  { id: "cook", name: "Cooking", category: "daily", mets: 2.5 },
  { id: "stand", name: "Standing", category: "daily", mets: 1.8 },
  { id: "carrychild", name: "Carrying child", category: "daily", mets: 4.0 },
  { id: "shovelsnow", name: "Shoveling snow", category: "daily", mets: 6.0 },
  { id: "mowlawn", name: "Mowing lawn", category: "daily", mets: 5.5 },
  { id: "carpentry", name: "Carpentry", category: "daily", mets: 3.5 },

  // Functional / misc
  { id: "stretch", name: "Stretching", category: "daily", mets: 2.3 },
  { id: "foamroll", name: "Foam rolling", category: "daily", mets: 2.5 },
  { id: "meditate", name: "Meditation", category: "daily", mets: 1.0 },
  { id: "sauna", name: "Sauna", category: "daily", mets: 1.5 },
  { id: "pushbike", name: "Push bike", category: "cardio", mets: 5.0 },
  { id: "treadmill", name: "Treadmill walk (incline)", category: "cardio", mets: 5.3 },
  { id: "spin", name: "Spin class", category: "cardio", mets: 8.5 },
  { id: "battle ropes", name: "Battle ropes", category: "cardio", mets: 10.5 },
  { id: "boxjump", name: "Box jump", category: "gym", mets: 7.5 },
];

export const CATEGORY_LABELS: Record<string, string> = {
  cardio: "Cardio",
  gym: "Gym",
  calisthenics: "Calisthenics",
  sports: "Sports",
  core: "Core",
  daily: "Daily",
};
