import type { FoodItem } from "./types";

export const FOODS: FoodItem[] = [
  { id: "egg", source: "seed", name: "Egg, whole", serving_size: 1, serving_unit: "egg", kcal: 78, protein_g: 6.3, fat_g: 5.3, carb_g: 0.6 },
  { id: "eggwhite", source: "seed", name: "Egg white", serving_size: 1, serving_unit: "egg", kcal: 17, protein_g: 3.6, fat_g: 0.1, carb_g: 0.2 },
  { id: "oats", source: "seed", name: "Rolled oats (dry)", serving_size: 40, serving_unit: "g", kcal: 150, protein_g: 5.4, fat_g: 2.7, carb_g: 27 },
  { id: "banana", source: "seed", name: "Banana", serving_size: 1, serving_unit: "medium", kcal: 105, protein_g: 1.3, fat_g: 0.4, carb_g: 27 },
  { id: "apple", source: "seed", name: "Apple", serving_size: 1, serving_unit: "medium", kcal: 95, protein_g: 0.5, fat_g: 0.3, carb_g: 25 },
  { id: "chickenbreast", source: "seed", name: "Chicken breast, cooked", serving_size: 100, serving_unit: "g", kcal: 165, protein_g: 31, fat_g: 3.6, carb_g: 0 },
  { id: "rice_white", source: "seed", name: "White rice, cooked", serving_size: 100, serving_unit: "g", kcal: 130, protein_g: 2.7, fat_g: 0.3, carb_g: 28 },
  { id: "rice_brown", source: "seed", name: "Brown rice, cooked", serving_size: 100, serving_unit: "g", kcal: 112, protein_g: 2.6, fat_g: 0.9, carb_g: 24 },
  { id: "broccoli", source: "seed", name: "Broccoli, steamed", serving_size: 100, serving_unit: "g", kcal: 35, protein_g: 2.4, fat_g: 0.4, carb_g: 7 },
  { id: "avocado", source: "seed", name: "Avocado", serving_size: 100, serving_unit: "g", kcal: 160, protein_g: 2, fat_g: 15, carb_g: 9 },
  { id: "almond", source: "seed", name: "Almonds", serving_size: 28, serving_unit: "g", kcal: 164, protein_g: 6, fat_g: 14, carb_g: 6 },
  { id: "peanutbutter", source: "seed", name: "Peanut butter", serving_size: 32, serving_unit: "g", kcal: 190, protein_g: 7, fat_g: 16, carb_g: 7 },
  { id: "milk_whole", source: "seed", name: "Milk, whole", serving_size: 240, serving_unit: "ml", kcal: 149, protein_g: 8, fat_g: 8, carb_g: 12 },
  { id: "milk_skim", source: "seed", name: "Milk, skim", serving_size: 240, serving_unit: "ml", kcal: 83, protein_g: 8, fat_g: 0.2, carb_g: 12 },
  { id: "greek_yogurt", source: "seed", name: "Greek yogurt, plain 0%", serving_size: 170, serving_unit: "g", kcal: 100, protein_g: 17, fat_g: 0.7, carb_g: 6 },
  { id: "salmon", source: "seed", name: "Salmon, cooked", serving_size: 100, serving_unit: "g", kcal: 208, protein_g: 20, fat_g: 13, carb_g: 0 },
  { id: "beef_lean", source: "seed", name: "Beef, lean ground 90%", serving_size: 100, serving_unit: "g", kcal: 176, protein_g: 20, fat_g: 10, carb_g: 0 },
  { id: "tofu", source: "seed", name: "Tofu, firm", serving_size: 100, serving_unit: "g", kcal: 144, protein_g: 17, fat_g: 9, carb_g: 3 },
  { id: "blackbeans", source: "seed", name: "Black beans, cooked", serving_size: 100, serving_unit: "g", kcal: 132, protein_g: 9, fat_g: 0.5, carb_g: 24 },
  { id: "sweetpotato", source: "seed", name: "Sweet potato, baked", serving_size: 100, serving_unit: "g", kcal: 90, protein_g: 2, fat_g: 0.1, carb_g: 21 },
  { id: "potato", source: "seed", name: "Potato, baked", serving_size: 100, serving_unit: "g", kcal: 93, protein_g: 2.5, fat_g: 0.1, carb_g: 21 },
  { id: "oliveoil", source: "seed", name: "Olive oil", serving_size: 14, serving_unit: "ml", kcal: 119, protein_g: 0, fat_g: 14, carb_g: 0 },
  { id: "tuna", source: "seed", name: "Tuna, canned in water", serving_size: 100, serving_unit: "g", kcal: 116, protein_g: 26, fat_g: 1, carb_g: 0 },
  { id: "whey", source: "seed", name: "Whey protein scoop", serving_size: 30, serving_unit: "g", kcal: 120, protein_g: 24, fat_g: 1.5, carb_g: 2 },
  { id: "bread_ww", source: "seed", name: "Whole wheat bread", serving_size: 1, serving_unit: "slice", kcal: 80, protein_g: 4, fat_g: 1.1, carb_g: 14 },
  { id: "tortilla", source: "seed", name: "Flour tortilla", serving_size: 1, serving_unit: "medium", kcal: 144, protein_g: 4, fat_g: 3.7, carb_g: 24 },
  { id: "cheese_cheddar", source: "seed", name: "Cheddar cheese", serving_size: 28, serving_unit: "g", kcal: 113, protein_g: 7, fat_g: 9, carb_g: 0.4 },
  { id: "spinach", source: "seed", name: "Spinach, raw", serving_size: 100, serving_unit: "g", kcal: 23, protein_g: 2.9, fat_g: 0.4, carb_g: 3.6 },
  { id: "tomato", source: "seed", name: "Tomato", serving_size: 1, serving_unit: "medium", kcal: 22, protein_g: 1.1, fat_g: 0.2, carb_g: 4.8 },
  { id: "onion", source: "seed", name: "Onion", serving_size: 100, serving_unit: "g", kcal: 40, protein_g: 1.1, fat_g: 0.1, carb_g: 9 },
  { id: "garlic", source: "seed", name: "Garlic, clove", serving_size: 1, serving_unit: "clove", kcal: 4, protein_g: 0.2, fat_g: 0, carb_g: 1 },
  { id: "coffee_black", source: "seed", name: "Black coffee", serving_size: 240, serving_unit: "ml", kcal: 2, protein_g: 0.3, fat_g: 0, carb_g: 0 },
  { id: "orange", source: "seed", name: "Orange", serving_size: 1, serving_unit: "medium", kcal: 62, protein_g: 1.2, fat_g: 0.2, carb_g: 15 },
  { id: "blueberries", source: "seed", name: "Blueberries", serving_size: 100, serving_unit: "g", kcal: 57, protein_g: 0.7, fat_g: 0.3, carb_g: 14 },
  { id: "strawberry", source: "seed", name: "Strawberries", serving_size: 100, serving_unit: "g", kcal: 32, protein_g: 0.7, fat_g: 0.3, carb_g: 8 },
  { id: "cottagecheese", source: "seed", name: "Cottage cheese 2%", serving_size: 113, serving_unit: "g", kcal: 80, protein_g: 11, fat_g: 2.5, carb_g: 5 },
  { id: "pasta", source: "seed", name: "Pasta, cooked", serving_size: 100, serving_unit: "g", kcal: 131, protein_g: 5, fat_g: 1.1, carb_g: 25 },
  { id: "pizza_slice", source: "seed", name: "Pizza cheese slice", serving_size: 1, serving_unit: "slice", kcal: 285, protein_g: 12, fat_g: 10, carb_g: 36 },
  { id: "burger", source: "seed", name: "Cheeseburger", serving_size: 1, serving_unit: "burger", kcal: 535, protein_g: 30, fat_g: 28, carb_g: 40 },
  { id: "chickennugget", source: "seed", name: "Chicken nuggets", serving_size: 100, serving_unit: "g", kcal: 296, protein_g: 15, fat_g: 19, carb_g: 18 },
  { id: "fries", source: "seed", name: "French fries", serving_size: 100, serving_unit: "g", kcal: 312, protein_g: 3.4, fat_g: 15, carb_g: 41 },
  { id: "darkchoc", source: "seed", name: "Dark chocolate 70%", serving_size: 28, serving_unit: "g", kcal: 156, protein_g: 2, fat_g: 12, carb_g: 13 },
  { id: "hummus", source: "seed", name: "Hummus", serving_size: 100, serving_unit: "g", kcal: 166, protein_g: 8, fat_g: 10, carb_g: 14 },
];